In [ ]:
from datetime import datetime

datetime.strptime("11/08/2026", "%d/%m/%Y").date()

datetime.date(2026, 8, 11)

In [14]:
datetime.strptime("11/08/2026", "%m/%d/%Y")

datetime.datetime(2026, 11, 8, 0, 0)

In [15]:
float("8.75") + 1

9.75

In [ ]:
row = {"Date": "11/08/2026", "Rate": "8.75"}

In [17]:
row["Date"]

'11/08/2026'

In [18]:
parsed_date = datetime.strptime(row["Date"], "%d/%m/%Y").date()
parsed_rate = float(row["Rate"])
parsed_date, parsed_rate

(datetime.date(2026, 8, 11), 8.75)

In [19]:
def parse_cbr_row(row):
    parsed_date = datetime.strptime(row["Date"], "%d/%m/%Y").date()
    parsed_rate = float(row["Rate"])
    return parsed_date, parsed_rate

In [20]:
parse_cbr_row(row)

(datetime.date(2026, 8, 11), 8.75)

In [ ]:
import sys

sys.path.append("..")
from data_access.contracts import CBRDecision
from datetime import date

In [ ]:
form = CBRDecision(decision_date=date(2026, 8, 11), rate=8.75)

display(form.decision_date)
form.rate

datetime.date(2026, 8, 11)

8.75

In [23]:
form.rate = 9.0

FrozenInstanceError: cannot assign to field 'rate'

In [25]:
def parse_cbr_row(row):
    parsed_date = datetime.strptime(row["Date"], "%d/%m/%Y").date()
    parsed_rate = float(row["Rate"])
    return CBRDecision(decision_date=parsed_date, rate=parsed_rate)

In [26]:
parse_cbr_row(row)

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

In [ ]:
pair = (date(2026, 8, 11), 8.75)
pair[1] = 9.0

TypeError: 'tuple' object does not support item assignment

In [27]:
row["Rate"] = "9.0"
row

{'Date': '11/08/2026', 'Rate': '9.0'}

In [28]:
pair[1]

NameError: name 'pair' is not defined

In [29]:
form.rate

8.75

In [ ]:
from data_access.parsers import parse_cbr_row

parse_cbr_row({"Date": "11/08/2026", "Rate": "8.75"})

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

In [ ]:
assert 1 + 1 == 2

In [ ]:
assert 1 + 1 == 3

AssertionError:

In [ ]:
from data_access.parsers import parse_cbr_row
from data_access.contracts import CBRDecision
from datetime import date

assert parse_cbr_row({"Date": "11/08/2026", "Rate": "8.75"}) == CBRDecision(
    decision_date=date(2026, 8, 11), rate=8.75
)

In [32]:
import pandas as pd

cbr_raw = pd.read_csv("../data/raw/cbr.csv")
cbr_raw.head()

         Date  Rate
0  11/08/2026  8.75
1  09/06/2026  8.75
2  08/04/2026  8.75
3  10/02/2026  8.75
4  09/12/2025  9.00

In [33]:
cbr_raw.dtypes

Date        str
Rate    float64
dtype: object

In [34]:
kcb_raw = pd.read_csv("../data/raw/kcb.csv")
kcb_raw.head()

         date  open  high   low  close  volume
0  1997-06-26  7.21  7.21  7.21   7.21  171517
1  1997-07-07  7.21  7.21  7.21   7.21  188297
2  1997-07-14  6.81  6.81  6.81   6.81   99620
3  1997-07-15  6.81  6.81  6.81   6.81  250000
4  1997-07-16  6.81  6.81  6.81   6.81  760268

In [35]:
kcb_raw.dtypes

date          str
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

In [36]:
first_cbr_row = cbr_raw.iloc[0].to_dict()
first_cbr_row

{'Date': '11/08/2026', 'Rate': 8.75}

In [37]:
parse_cbr_row(first_cbr_row)

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

In [38]:
first_kcb_row = kcb_raw.iloc[0].to_dict()
first_kcb_row

{'date': '1997-06-26',
 'open': 7.21,
 'high': 7.21,
 'low': 7.21,
 'close': 7.21,
 'volume': 171517}

In [39]:
datetime.strptime(first_kcb_row["date"], "%Y-%m-%d").date()

datetime.date(1997, 6, 26)

In [ ]:
from data_access.parsers import parse_kcb_row

parse_kcb_row(first_kcb_row)

KCBDailyPrice(trade_date=datetime.date(1997, 6, 26), open_price=7.21, high_price=7.21, low_price=7.21, close_price=7.21, volume=171517)