In [2]:
from datetime import datetime

datetime.strptime("11/08/2026", "%d/%m/%Y").date()

datetime.date(2026, 8, 11)

In [3]:
datetime.strptime("11/08/2026", "%m/%d/%Y")

datetime.datetime(2026, 11, 8, 0, 0)

In [4]:
float("8.75") + 1

9.75

In [5]:
row = {"Date": "11/08/2026", "Rate": "8.75"}

In [6]:
row["Date"]

'11/08/2026'

In [7]:
parsed_date = datetime.strptime(row["Date"], "%d/%m/%Y").date()
parsed_rate = float(row["Rate"])
parsed_date, parsed_rate

(datetime.date(2026, 8, 11), 8.75)

In [8]:
def parse_cbr_row(row):
    parsed_date = datetime.strptime(row["Date"], "%d/%m/%Y").date()
    parsed_rate = float(row["Rate"])
    return parsed_date, parsed_rate

In [9]:
parse_cbr_row(row)

(datetime.date(2026, 8, 11), 8.75)

In [4]:
import sys

sys.path.append("..")
from data_access.contracts import CBRDecision
from datetime import date

In [11]:
form = CBRDecision(decision_date=date(2026, 8, 11), rate=8.75)

display(form.decision_date)
form.rate

datetime.date(2026, 8, 11)

8.75

In [12]:
form.rate = 9.0

FrozenInstanceError: cannot assign to field 'rate'

In [13]:
def parse_cbr_row(row):
    parsed_date = datetime.strptime(row["Date"], "%d/%m/%Y").date()
    parsed_rate = float(row["Rate"])
    return CBRDecision(decision_date=parsed_date, rate=parsed_rate)

In [14]:
parse_cbr_row(row)

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

In [15]:
pair = (date(2026, 8, 11), 8.75)
pair[1] = 9.0

TypeError: 'tuple' object does not support item assignment

In [16]:
row["Rate"] = "9.0"
row

{'Date': '11/08/2026', 'Rate': '9.0'}

In [17]:
pair[1]

8.75

In [18]:
form.rate

8.75

In [19]:
from data_access.parsers import parse_cbr_row

parse_cbr_row({"Date": "11/08/2026", "Rate": "8.75"})

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

In [20]:
assert 1 + 1 == 2

In [21]:
assert 1 + 1 == 3

AssertionError:

In [22]:
from data_access.parsers import parse_cbr_row
from data_access.contracts import CBRDecision
from datetime import date

assert parse_cbr_row({"Date": "11/08/2026", "Rate": "8.75"}) == CBRDecision(
    decision_date=date(2026, 8, 11), rate=8.75
)

In [23]:
import pandas as pd

cbr_raw = pd.read_csv("../data/raw/cbr.csv")
cbr_raw.head()

         Date  Rate
0  11/08/2026  8.75
1  09/06/2026  8.75
2  08/04/2026  8.75
3  10/02/2026  8.75
4  09/12/2025  9.00

In [24]:
cbr_raw.dtypes

Date        str
Rate    float64
dtype: object

In [25]:
kcb_raw = pd.read_csv("../data/raw/kcb.csv")
kcb_raw.head()

         date  open  high   low  close  volume
0  1997-06-26  7.21  7.21  7.21   7.21  171517
1  1997-07-07  7.21  7.21  7.21   7.21  188297
2  1997-07-14  6.81  6.81  6.81   6.81   99620
3  1997-07-15  6.81  6.81  6.81   6.81  250000
4  1997-07-16  6.81  6.81  6.81   6.81  760268

In [26]:
kcb_raw.dtypes

date          str
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

In [27]:
first_cbr_row = cbr_raw.iloc[0].to_dict()
first_cbr_row

{'Date': '11/08/2026', 'Rate': 8.75}

In [28]:
parse_cbr_row(first_cbr_row)

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

In [29]:
first_kcb_row = kcb_raw.iloc[0].to_dict()
first_kcb_row

{'date': '1997-06-26',
 'open': 7.21,
 'high': 7.21,
 'low': 7.21,
 'close': 7.21,
 'volume': 171517}

In [30]:
datetime.strptime(first_kcb_row["date"], "%Y-%m-%d").date()

datetime.date(1997, 6, 26)

In [31]:
from data_access.parsers import parse_kcb_row

parse_kcb_row(first_kcb_row)

KCBDailyPrice(trade_date=datetime.date(1997, 6, 26), open_price=7.21, high_price=7.21, low_price=7.21, close_price=7.21, volume=171517)

In [32]:
import csv

with open("../data/raw/cbr.csv", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)
    rows = list(reader)

display(len(rows))
rows[0]

124

{'Date': '11/08/2026', 'Rate': '8.75'}

In [33]:
with open("../data/raw/kcb.csv", encoding="utf-8-sig") as f:
    reader = csv.DictReader(f)
    kcb_rows = list(reader)

display(len(kcb_rows))
kcb_rows[0]

6810

{'date': '1997-06-26',
 'open': '7.21',
 'high': '7.21',
 'low': '7.21',
 'close': '7.21',
 'volume': '171517'}

In [34]:
decisions = [parse_cbr_row(row) for row in rows]
len(decisions)

124

In [35]:
display(decisions[0])
decisions[-1]

CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75)

CBRDecision(decision_date=datetime.date(2008, 8, 6), rate=9.0)

In [36]:
prices = [parse_kcb_row(row) for row in kcb_rows]
len(prices)

6810

In [37]:
reader

In [38]:
prices = [parse_kcb_row(row) for row in reader]
prices[0]

ValueError: I/O operation on closed file.

In [39]:
from data_access.parsers import load_cbr_decisions, load_kcb_prices

all_decisions = load_cbr_decisions("../data/raw/cbr.csv")
all_prices = load_kcb_prices("../data/raw/kcb.csv")

len(all_decisions), len(all_prices)

(124, 6810)

In [1]:
from collections import Counter

fruits = ["mango", "banana", "mango", "orange", "mango"]

Counter(fruits)

Counter({'mango': 3, 'banana': 1, 'orange': 1})

In [2]:
tally = Counter(fruits)
duplicates = [item for item, count in tally.items() if count > 1]
duplicates

['mango']

In [ ]:
from data_access.parsers import load_cbr_decisions

all_decisions = load_cbr_decisions("../data/raw/cbr.csv")
len(all_decisions)

124

In [10]:
all_decisions[0:3]

[CBRDecision(decision_date=datetime.date(2026, 8, 11), rate=8.75),
 CBRDecision(decision_date=datetime.date(2026, 6, 9), rate=8.75),
 CBRDecision(decision_date=datetime.date(2026, 4, 8), rate=8.75)]

In [9]:
dates = [decision.decision_date for decision in all_decisions]
len(dates)

124

In [11]:
dates[0:2]

[datetime.date(2026, 8, 11), datetime.date(2026, 6, 9)]

In [12]:
tally = Counter(dates)
duplicates = [date_val for date_val, count in tally.items() if count > 1]
duplicates

[datetime.date(2020, 5, 27), datetime.date(2019, 5, 27)]

In [13]:
[decision for decision in all_decisions if decision.decision_date == date(2019, 5, 27)]

[CBRDecision(decision_date=datetime.date(2019, 5, 27), rate=9.0),
 CBRDecision(decision_date=datetime.date(2019, 5, 27), rate=9.0)]

In [14]:
[decision for decision in all_decisions if decision.decision_date == date(2020, 5, 27)]

[CBRDecision(decision_date=datetime.date(2020, 5, 27), rate=7.0),
 CBRDecision(decision_date=datetime.date(2020, 5, 27), rate=7.0)]

In [15]:
class Fruit:
    pass

In [16]:
mango = Fruit()
mango

In [17]:
mango.name = "mango"
mango.count = 3
mango.name

'mango'

In [19]:
banana = Fruit()
banana.name = "banana"
banana.count = 5

mango.name, banana.name

('mango', 'banana')

In [20]:
guest_list = set()
guest_list

set()

In [21]:
guest_list.add("Alice")
guest_list.add("James")
guest_list.add("Alice")
guest_list

{'Alice', 'James'}

In [22]:
"Alice" in guest_list

True

In [ ]:
names = ["Alice", "Bob", "Alice", "Charlie"]

seen = set()
unique_names = []

for name in names:
    if name not in seen:
        unique_names.append(name)
        seen.add(name)

unique_names

['Alice', 'Bob', 'Charlie']

In [24]:
seen = set()
unique_names = []

seen, unique_names

(set(), [])

In [25]:
name = "Alice"
name not in seen

True

In [26]:
unique_names.append(name)
seen.add(name)
unique_names, seen

(['Alice'], {'Alice'})

In [27]:
names

['Alice', 'Bob', 'Alice', 'Charlie']

In [29]:
list(set(names))

['Bob', 'Alice', 'Charlie']

In [30]:
seen

{'Alice'}

In [ ]:
seen.add("Bob")
seen.add("Alice")
seen.add("Charlie")

In [32]:
seen

{'Alice', 'Bob', 'Charlie'}

In [33]:
list(seen)

['Bob', 'Alice', 'Charlie']

In [34]:
for name in seen:
    if name in seen:
        unique_names.append(name)

In [35]:
unique_names

['Alice', 'Bob', 'Alice', 'Charlie']

In [36]:
deduplicated_names = []
for name in seen:
    deduplicated_names.append(name)

In [37]:
deduplicated_names

['Bob', 'Alice', 'Charlie']

In [38]:
seen

{'Alice', 'Bob', 'Charlie'}

In [44]:
unique_names_2 = []

In [45]:
seen = set()
seen

set()

In [41]:
names

['Alice', 'Bob', 'Alice', 'Charlie']

In [46]:
for name in names:
    seen.add(name)
    if name in seen:
        unique_names_2.append(name)

unique_names_2

['Alice', 'Bob', 'Alice', 'Charlie']

In [48]:
seen = set()
unique_names_2 = []

seen, unique_names_2

(set(), [])

In [49]:
name = "Alice"
seen.add(name)
seen

{'Alice'}

In [50]:
name in seen

True

In [51]:
seen = set()
unique_names_2 = []

for name in names:
    if name not in seen:
        unique_names_2.append(name)
        seen.add(name)

unique_names_2

['Alice', 'Bob', 'Charlie']

In [52]:
seen = set()
clean_decisions = []

for decision in all_decisions:
    if decision.decision_date not in seen:
        clean_decisions.append(decision)
        seen.add(decision.decision_date)

len(all_decisions), len(clean_decisions)

(124, 122)

In [53]:
import sys

sys.path.append("..")
from data_access.validation import deduplicate_cbr_decisions

clean = deduplicate_cbr_decisions(all_decisions)
len(clean)

122